# https://github.com/BetaHuhn/repo-file-sync-action

group:
  - files:
      - ".editorconfig"
      - "CODE_OF_CONDUCT.md"
      - "CONTRIBUTING.md"
      - "LICENSE"
    repos: |
      cv-schema/builder
      cv-schema/cv-schema.github.io
      cv-schema/schema
